# Generated by Django 5.2.4 on 2025-08-16 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_transactions_balance_after_transactions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='account_no',
            field=models.IntegerField(blank=True, default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transactions',
            name='transaction_type',
            field=models.IntegerField(choices=[(1, 'Deposite'), (2, 'Withdrawal'), (3, 'Loan'), (4, 'Loan Paid'), (5, 'Transfer Money')], null=True),
        ),
    ]
