# Generated by Django 5.2.4 on 2025-08-16 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_transactions_account_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='account_no',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
